[package]
name = "heartbeat-windows"
description = "Heartbeat client for Windows. Can be used as an action in Task Scheduler."
license = "MPL-2.0"
authors = ["VJ <root@5ht2.me>"]
repository = "https://github.com/lmaotrigine/heartbeat-windows"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.44"
dirs = "5.0.1"
serde = { version = "1.0.183", features = ["derive"] }
toml = { version = "0.7.6", default-features = false, features = ["parse"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.17"

[features]
task_scheduler = []

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'
strip = true
codegen-units = 1
