[package]
name = "heartbeat-windows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
serde = { version = "1.0.183", features = ["derive"] }
toml = { version = "0.7.6", default-features = false, features = ["parse"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.17"
ureq = "2.7.1"

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'
strip = 'debuginfo'
codegen-units = 1
