max_width = 120
newline_style = "Unix"  # yeah, I know.
use_field_init_shorthand = true
use_try_shorthand = true

# unstable options that help catching mistakes in formatting and that we want to enable
# when they become stable.
#
# they are kept here since they are useful to run from time to time.
#format_code_in_doc_comments = true
#format_strings = true
#reorder_impl_items = true
#comment_width = 80
#wrap_comments = true
#normalize_comments = true
